version: '3.9'

volumes:
  postgres-data: null

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=roley
      - POSTGRES_PASSWORD=localPassword
      - POSTGRES_DB=roley
    volumes:
      - postgres-data:/var/lib/postgresql/data
